{
 "title": "Evidently-drift Dashboard",
 "description": "Visualizing Evidently Data",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "description": "The graph of the number of drifted columns",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values ",
   "type": "timeseries",
   "description": "The share nelof missing values pa",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "description": "The prediction drift panel visualization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}